core/urls.py
from django.conf.urls import url
from django.contrib import admin
from core import views
from django.contrib.auth import views as auth_views
from .views import EditPersonalInfoView, EditFinancialInfoView

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^account-setup/$', views.account_setup, name='account-setup'),
    url(r'^history/$', views.history, name='history'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^financials/$', views.financials, name='financials'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^edit-profile/', EditPersonalInfoView.as_view(), name="edit_profile"),
    url(r'^edit-financials/', EditFinancialInfoView.as_view(), name="edit-financials"),
    url(r'^lease-apply/$', views.lease_apply, name='lease-apply'),
    url(r'^join-group/$', views.join_group, name='join-group'),
    url(r'^viewinfo/(?P<share_key>[^/]+)/$', views.leaser_view, name='leaser_view'),
    url(r'^superadmin/$', views.superadmin, name='superadmin')
]

guvhacks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals
from .creditScore import creditScore

def getUpdatedCreditScore(user):
	#country, curIncMo, curHouseExp,workExp, bankAcc, bankBal, cashBal,arrLenMo,outDebt, outDebtAmt, outDebtTerm, paidDebt, misPay, misPayFreq
	account = user.account
	financials = FinancialInfo.objects.get(account=account)
	country = account.country
	curIncMo = financials.monthly_income
	curHouseExp = financials.housing_expense
	workExp = Employment.objects.filter(account=account).exists()
	bankAcc = financials.has_bank_account
	bankBal = financials.amount_in_bank
	cashBal = financials.amount_cash
	arrLenMo = financials.time_in_europe
	outDebt = financials.ongoing_debt
	outDebtAmt = financials.amount_debts
	outDebtTerm = financials.num_months_debt
	# the user has previously had debt and it is not ongoing, meaning it has been repaid
	paidDebt = financials.has_debts and (not financials.ongoing_debt) 
	misPay = (financials.missed_payments != 0)
	misPayFreq = financials.missed_payments

	credit_score = creditScore(curIncMo, curHouseExp, workExp, bankAcc, bankBal, cashBal,arrLenMo,outDebt, outDebtAmt, outDebtTerm, paidDebt, misPay, misPayFreq)

	return credit_score

COUNTRIES = (('Italy', 'Italy'),
			 ('France', 'France'),
			 ('Germany', 'Germany')
			)

REASONS = (('health', 'Health'),
			 ('lost_job', 'Lost Job'),
			 ('migration_issues', 'Migration Issues'),
			 ('other', 'Other')
			)

GENDERS = (('Male', 'Male'),
			('Female', 'Female'))

class Account(models.Model):
	# Link to the Django user account
	user = models.OneToOneField(User, on_delete=models.CASCADE)

	name = models.CharField(max_length=256)
	phone = models.CharField(max_length=100) # function to verify real phone number in form?
	address = models.CharField(max_length=256) # change to multiple lines, etc?
	city = models.CharField(max_length=256)
	gender = models.CharField(max_length=10, choices=GENDERS)
	age = models.IntegerField()
	country = models.CharField(max_length=256, choices=COUNTRIES)
	profile_photo = models.FileField(null=True, upload_to="profile_photos/")
	credit_score = models.IntegerField(blank=True, null=True)

	applied_for_lease = models.BooleanField(default=False)
	has_lease = models.BooleanField(default=False)

	share_key = models.CharField(max_length=16, blank=True, null=True)


class Employment(models.Model):
	account = models.ForeignKey(Account)
	employer = models.CharField(max_length=256)
	paystub = models.FileField(blank=True, null=True, upload_to="paystubs/")
	phone = models.CharField(max_length=100) # function to verify real phone number in form?
	start_date = models.DateField()
	end_date = models.DateField(blank=True, null=True)
	currently_employed = models.BooleanField(default=False, verbose_name="Currently Employed")
	monthly_salary = models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Monthly Salary")
	
	#make automatic updating of credit score
	@staticmethod
	def post_save(sender, **kwargs):
		instance = kwargs.get('instance')
		created = kwargs.get('created')
		if FinancialInfo.objects.filter(account=instance.account).exists():
			
			score = getUpdatedCreditScore(instance.account.user)
			instance.account.credit_score = score
			instance.account.save()
			print("Updating score:",score,"\nScore on account is:",instance.account.credit_score)


class Identification(models.Model):
	account = models.OneToOneField(Account)
	name = models.CharField(max_length=100)
	file = models.FileField(upload_to='id_documents/')


class FinancialInfo(models.Model):
	account = models.OneToOneField(Account)

	monthly_income = models.DecimalField(decimal_places=2, max_digits=12, default=0)
	housing_expense = models.DecimalField(decimal_places=2, max_digits=12, default=0)
	
	time_in_europe = models.IntegerField() # in months
	
	has_bank_account = models.BooleanField(default=False)
	amount_in_bank = models.DecimalField(decimal_places=2, max_digits=12, default=0)
	amount_cash = models.DecimalField(decimal_places=2, max_digits=12,blank=True, null=True,default=0)

	has_debts = models.BooleanField(default=False)
	amount_debts = models.DecimalField(decimal_places=2, max_digits=12, blank=True, default=0)
	num_months_debt = models.IntegerField(blank=True, null=True, default=0)
	ongoing_debt = models.BooleanField(default=False)
	reason_ongoing = models.CharField(max_length=256, choices=REASONS, blank=True, null=True)

	# What more needs to go here?
	missed_payments = models.IntegerField(blank=True, null=True, default=0)

	loan_file = models.FileField(upload_to="loan_docs/", blank=True, null=True)

	#make automatic updating of credit score
	@staticmethod
	def post_save(sender, **kwargs):
		instance = kwargs.get('instance')
		created = kwargs.get('created')
		score = getUpdatedCreditScore(instance.account.user)
		instance.account.credit_score = score
		instance.account.save()
		print("Updating score:",score,"\nScore on account is:",instance.account.credit_score)


class Group(models.Model):
	code = models.CharField(max_length=256)


class Lease(models.Model):
	account = models.OneToOneField(Account)

	amount = models.DecimalField(decimal_places=2, max_digits=12, default=0)
	leaser_name = models.CharField(max_length=256)
	leaser_email = models.CharField(max_length=256)

	guarantor_name = models.CharField(max_length=256, blank=True, null=True)
	gurantor_email = models.CharField(max_length=256, blank=True, null=True)

	duration = models.IntegerField(default=12) # in months
	payments_made = models.IntegerField(default=0, blank=True) # in months

	months_left_in_current_job = models.IntegerField(default=0)

	group = models.ForeignKey(Group, blank=True, null=True)

	approved = models.BooleanField(default=False)

	risk_profile_string = models.CharField(max_length=1024,null=True,blank=True)

signals.post_save.connect(Employment.post_save, sender=Employment)
signals.post_save.connect(FinancialInfo.post_save, sender=FinancialInfo)

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import random
import string

from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.views.generic import UpdateView
from .creditScore import creditScore
from django.core.mail import send_mail

from .defaultModel import applicant,individualDefaultRatio
from core.forms import *
from core.models import *

import json

@login_required(login_url='/login/')
def index(request):

	context = {'user': request.user,
			   'credit_score': request.user.account.credit_score}
	
	return render(request, 'core/index.html', context)


def register(request):

	user_form = UserForm()
	context = {'user_form': user_form}

	if request.method == 'POST':
		form = UserForm(request.POST)
		if form.is_valid():
			user = User.objects.create_user(username=form.cleaned_data['username'],
											email=form.cleaned_data['email'],
											password=form.cleaned_data['password'])
			messages.add_message(request, messages.SUCCESS, 'Account created.')
			return redirect('login')
		else:
			messages.add_message(request, messages.ERROR, 'Invalid form.')

	return render(request, 'core/register.html', context)


def login(request):
	
	login_form = LoginForm()
	context = {'login_form': login_form}

	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			#user = authenticate(username=form.cleaned_data.get('username'), 
			#					password=form.cleaned_data.get('password'))
			user = authenticate(username=request.POST.get('username'), 
									password=request.POST.get('password'))

			if user is not None:
				auth_login(request, user)
				if not Account.objects.filter(user=request.user).exists():
					return redirect('account-setup')
				else:
					return redirect('/')
			else:
				messages.add_message(request, messages.ERROR, 'Invalid login credentials.')
				return redirect('/login/')
		else:
			print(form.errors)
			messages.add_message(request, messages.ERROR, 'Invalid form')
			return redirect('/login/')

	return render(request, 'core/login.html', context)


@login_required(login_url='login')
def account_setup(request):

	account_form = AccountForm()
	context = {'account_form': account_form}

	if request.method == 'POST':
		form = AccountForm(request.POST, request.FILES)
		if form.is_valid():
			account = form.save(commit=False)
			account.user = request.user
			account.save()
			return redirect('history')
		else:
			print(form.errors)
			messages.add_message(request, messages.ERROR, 'Invalid form')			

	return render(request, 'core/account-setup.html', context)


@login_required(login_url='login')
def history(request):

	employment_form = EmploymentForm()
	prev_employment = Employment.objects.filter(account=request.user.account)
	file_form = IdentificationForm()
	# prefill if it already exists, and dont create a new one
	fin_info_form = FinancialInfoForm()

	context = {'employment_form': employment_form,
			   'employment': prev_employment,
			   'file_form': file_form,
			   'user': request.user,
			   'fin_info_form': fin_info_form}

	if request.method == 'POST':
		action = request.POST.get('action')
		print(action)
		if action == 'add_employment':
			form = EmploymentForm(request.POST)
			if form.is_valid():
				employment = form.save(commit=False)
				employment.account = request.user.account
				employment.save()
				messages.add_message(request, messages.SUCCESS, 'Employment Added')
			else:
				print(form.errors)
				messages.add_message(request, messages.ERROR, 'Invalid form')
		elif action == 'add_id':
			form = IdentificationForm(request.POST, request.FILES)
			if form.is_valid() and not Identification.objects.filter(account=request.user.account).exists():
				identification = form.save(commit=False)
				identification.account = request.user.account
				identification.save()
				messages.add_message(request, messages.SUCCESS, 'ID Added')
			else:
				print(request.user.account.id)
		elif action == 'fin_info':
			form = FinancialInfoForm(request.POST)
			if form.is_valid():
				fin_info = form.save(commit=False)
				fin_info.account = request.user.account
				fin_info.save()
				messages.add_message(request, messages.SUCCESS, 'Information saved.')
				credit_score = getUpdatedCreditScore(request.user)
				print(credit_score)
				request.user.account.credit_score = credit_score
				request.user.account.save()
			else:
				print(form.errors)

	return render(request, 'core/history.html', context)


@login_required(login_url='login')
def profile(request):

	profile = request.user.account
	
	if request.method == 'POST':
		action = request.POST.get('action')
		if action == 'share':
			if profile.share_key is None:
				profile.share_key = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(16))
				print(profile.share_key)
				profile.save()
				# send email to leaser
			email = request.POST.get('email')
			print(email)
			send_mail(
				'Credit/Ability Score for ' + str(profile.name),
				'View the creditability score for ' + str(profile.name) + ' here: localhost:8000/viewinfo/' + profile.share_key,
				'mailer@creditability.com',
				[email],
				fail_silently=False,
			)
			messages.add_message(request, messages.SUCCESS, 'Message Sent!')
		elif action == 'reset':
			profile.share_key = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(16))
			print(profile.share_key)
			profile.save()

	context = {'profile': profile}
	return render(request, 'core/profile.html', context)


class EditPersonalInfoView(UpdateView):
    model = Account
    form_class = AccountForm
    template_name = "core/edit-profile.html"

    def get_object(self, *args, **kwargs):
        user = self.request.user

        return user.account

    def get_success_url(self, *args, **kwargs):
        return reverse('profile')



@login_required(login_url='login')
def financials(request):

	#check if a financial profile exists for this user--page load will fail without one
	if not FinancialInfo.objects.filter(account=request.user.account).exists():
		return redirect('/history/')
	else:
		#otherwise...
		employment_form = EmploymentForm()
		financials = FinancialInfo.objects.get(account=request.user.account)
		account = request.user.account
		context = {'account': account,
				   'financials': financials,
				   'employment_form': employment_form}


		if request.method == 'POST':
			action = request.POST.get('action')
			print(action)
			if action == 'add_employment':
				form = EmploymentForm(request.POST)
				if form.is_valid():
					employment = form.save(commit=False)
					employment.account = request.user.account
					employment.save()
					messages.add_message(request, messages.SUCCESS, 'Employment Added')
				else:
					print(form.errors)
					messages.add_message(request, messages.ERROR, 'Invalid form')
			elif action == 'delete_employment':
				pk = request.POST.get('pk')
				employment = Employment.objects.get(pk=pk)
				employment.delete()


		return render(request, 'core/financials.html', context)


class EditFinancialInfoView(UpdateView):
    model = FinancialInfo
    form_class = FinancialInfoForm
    template_name = "core/edit-financials.html"

    def get_object(self, *args, **kwargs):
        user = self.request.user
        financials = FinancialInfo.objects.get(account=user.account)

        return financials

    def get_success_url(self, *args, **kwargs):
        return reverse('financials')


@login_required(login_url='login')
def faq(request):
	context = {}
	return render(request, 'core/faq.html', context)


@login_required(login_url='login')
def lease_apply(request):
	lease_form = LeaseForm()

	context = {'lease_form': lease_form,
			   'account': request.user.account}
	if request.method == 'POST':
		action = request.POST.get('action')
		if action == 'lease-app':
			form = LeaseForm(request.POST)
			if form.is_valid():
				lease = form.save(commit=False)
				lease.account = request.user.account
				#lease.save() not yet!
				messages.add_message(request, messages.SUCCESS, 'Application submitted!')
				request.user.account.applied_for_lease = True
				request.user.account.save()

				#perform a risk profile calculation using Yanchen's tool
				print("Leaser risk profile calculation:")
				acct = request.user.account

				empInfo = Employment.objects.filter(account = acct)
				employed=False
				for emp in empInfo:
					if emp.currently_employed:
						employed = True
				finInfo = FinancialInfo.objects.get(account = acct)
				bankBal = finInfo.amount_in_bank
				income = finInfo.monthly_income
				#secondary check
				if not employed:
					income = 0
				remainTerm = lease.months_left_in_current_job

				a = applicant(employed,income,bankBal,remainTerm,income)
				res = individualDefaultRatio(a,lease.amount,lease.duration)
				print(res)

				#save the risk profile data to this lease and save the lease
				lease.risk_profile_string = json.dumps(res)
				lease.save()

				return redirect('index')


	return render(request, 'core/lease-apply.html', context)


@login_required(login_url='login')
def join_group(request):
	join_form = JoinGroupForm()
	create_form = CreateGroupForm()

	if request.method == 'POST':
		action = request.POST.get('action')
		if action == 'join':
			form = JoinGroupForm(request.POST)
			if form.is_valid():
				my_code = form.cleaned_data['code']
				if Group.objects.filter(code=my_code).exists():
					group = Group.objects.get(code=my_code)
					lease = Lease.objects.get(account=request.user.account)
					if lease.group is None:
						lease.group = group
						lease.save()
					else:
						messages.add_message(request, messages.ERROR, "You are already in a group.")
				else:

core/templates/core/account-setup.html
{% extends 'core/base/base.html' %}

{% block content %}
  <h1>Account Details</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ account_form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

core/templates/core/edit-financials.html
{% extends 'core/base/base.html' %}

{% block content %}

<h1>Edit Financials</h1>
<hr>

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" class="btn btn-primary" value="Save">
</form>


{% endblock %}

core/templates/core/edit-profile.html
{% extends 'core/base/base.html' %}

{% block content %}

<h1>Edit Profile</h1>
<hr>

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" class="btn btn-primary" value="Save">
</form>


{% endblock %}

core/templates/core/faq.html
{% extends 'core/base/base.html' %}

{% block content %}

<h1>FAQ's</h1>
<hr>

<p><b>What does my credibility score mean?</b></p>
<p>Your score is based on your previous history of rent, loan, and household payments and any proof of incomes you are able to provide. Your score shows how successfully you have been able to maintain strong finances and pay back any debts. A “Good” or “Excellent” score shows a potential landlord, employer, or even roommate how reliable you are in case you do not have the papers or documents to prove that you are able to make repayments. </p>

<p>Your score is calculated out of 100. If the information on your financial and employment history cannot be verified, you will start with a score of 0 until we can help you build up your score.</p> 

<p><b>Why is my score negative? How can I change this?</b></p>

<p>If your previous documents or your verification process shows that:</p> 

<p>You missed more than 2 loan or rent repayments OR
Your household expenditures (rent and how much you pay for expenses) is higher than your average income</p> 

<p>… then your score is calculated as a negative. Don’t worry, there are ways to improve this! See here for more information.</p> 

<p><b>I got a new job. How do I update this?</b></p>
<p>Congratulations!! Click on “Profile” and edit whatever information you have updated. After this is verified, you may see an increase in your credibility score.</p> 

<p><b>How can I use my score? What if someone has questions about my score?</b></p>
<p>You can send your profile and score to anyone asking for proof of employment, ability to pay, or in any scenario where you may not be able to provide documents to match requirements. If you have a strong score, this can show your landlord, potential employer, or potential lender that you are able to make repayments even if you are </p> 

<p><b>Who can see my score?</b></p>
<p>Your score can only be shared by people you wish to share your score with. For example, if a landlord is asking for proof that you can make repayments, you can send them a link to your profile. </p> 

<p>Here, they will only see what parts of your profile you agree to share with them. For example, if you do not want your landlord to see you worked in a restaurant, you can hide this and they will only see that your employment was verified and for how long you worked there.</p> 

<p><b>What is “Lease Support”? Will you help pay my rent?</b></p>
<p>If you are confident you can pay your rent, but are unable to prove this to your landlord, you can apply for “lease support” from us. Lease support will help you get a “guarantor” or a 3rd party organization that will co-sign the lease with you. You are still responsible for all rent payments, but the 3rd party organization will help tell the landlord that they trust you to make the repayments. If you are unable to pay rent one month, the 3rd party organization will provide the rent for 1 month and this will have to be repaid by you later.</p> 

<p>If your application for lease support is accepted, we will help you contact the guarantor and finalize this partnership.</p> 

<p><b>What is “Group Insurance and Savings?”</b></p>
<p>You can choose to add group insurance to your lease if you are approved. Group insurance helps you choose a group of friends to add a collective insurance. Each month, 5% of your rent will be deposited in a collective savings pool. If anyone in your group does not make their payment, the collective pool will be subtracted and used to fund their rent payments. If everyone makes payments successfully throughout their lease, your savings will be returned to you at the end of your lease.</p> 



{% endblock %}

core/templates/core/financials.html
{% extends 'core/base/base.html' %}

{% block content %}

<h1>{{ user.account.name }}'s Financial Information</h1>

<hr>

<table class="table">
  	<thead>
  		<th>Employer</th>
  		<th>Start Date</th>
  		<th>End Date</th>
  		<th>Currently Employed</th>
  		<th>Wage</th>
  		<th>Delete</th>
  	</thead>
  	<tbody>
  		{% for entry in account.employment_set.all %}
  		<tr>
  			<td>{{ entry.employer }}</td>
  			<td>{{ entry.start_date }}</td>
  			<td>{{ entry.end_date }}</td>
  			<td>{{ entry.currently_employed }}</td>
  			<td>{{ entry.wage }}</td>
  			<td>
  				<form method="post">
  					{% csrf_token%}
  					<input type="hidden" name="action" value="delete_employment">
  					<input type="hidden" name="pk" value="{{entry.pk}}">
  					<button type="submit" class="btn btn-danger">Delete Job</button>
  				</form>
  			</td>
  		</tr>
  		{% endfor %}
  	</tbody>
  </table>

		<!-- Button trigger modal -->
	<button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#employmentModal">
	  Add previous employment
	</button>

  <hr>
  <br>
  <h4>Income and Expenses</h4>

  <p>Monthly Income: {{ financials.monthly_income }}</p>
  <p>Monthly Housing Expenses: {{ financials.housing_expense }}</p>

  <br>
  <h4>Bank Info</h4>

  <p>Has Bank Account: {{ financials.has_bank_account }}</p>
  <p>Amount in Account: {{ financials.amount_in_bank }}</p>
  <p>Amount in Cash: {{ financials.amount_cash }}</p>

  <br>
  <h4>Time in Country</h4>

  <p>Months spent in country: {{ financials.time_in_europe }}</p>

  <br>
  <h4>Previous Debts</h4>
  <p>Has Debt: {{ financials.has_debts }}</p>
  <p>Amount Debt: {{ financials.amount_debts }}</p>
  <p>Number of months of debt: {{ financials.num_months_debt }}</p>
  <p>Is the debt ongoing? {{ financials.ongoing_debt }}</p>
  <p>Why is the debt ongoing? {{ financials.reason_ongoing }}</p>
  <p>Number of missed payments: {{ financials.missed_payments }}</p>
  {% if financials.loan_file %}
    <p>Loan file: <img src="{{ financials.loan_file.url }}" style="width:50%"></p>
  {% endif %}

  <a href="{% url 'edit-financials' %}" class="btn btn-primary">Edit</a>


  <!-- Employment Modal -->
<div class="modal fade" id="employmentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Employment History</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post">
	      <div class="modal-body">
	      		{% csrf_token %}
	        	{{ employment_form.as_p }}
	        	<input type="hidden" name="action" value="add_employment">
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        <button type="submit" class="btn btn-primary">Add</button>
	      </div>
  	  </form>
    </div>
  </div>
</div>


{% endblock %}

core/templates/core/join-group.html
{% extends 'core/base/base.html' %}

{% block content %}
  <h1>Join a Group</h1>
  <hr>

  {% if account.has_lease %}
  	<h4>Create a new Group</h4>
  	<form method="post">
  		{% csrf_token %}
  		{{ create_form.as_p }}
  		<input type="hidden" name="action" value="create">
  		<button type="submit" class="btn btn-primary">Create</button>
  	</form>

  	<hr>
  	<h4>Join an Existing Group</h4>
  	  <form method="post">
  		{% csrf_token %}
  		{{ join_form.as_p }}
  		 <input type="hidden" name="action" value="join">
  		<button type="submit" class="btn btn-primary">Join</button>
  	</form>

  {% else %}
  	<p>You must be in a lease to join a rotating credit insurance group.</p>
  {% endif %}

{% endblock %}

core/templates/core/lease-apply.html
{% extends 'core/base/base.html' %}

{% block content %}
  <h1>Apply for Lease Support</h1>
  <hr>

  {% if account.applied_for_lease %}
  	<p>You have already applied for a lease.</p>
  {% else %}

<p>You are applying for Lease Support.</p>

<p>What is Lease Support?</p>
<p>If you are confident you can pay your rent, but are unable to prove this to your landlord, you can apply for “lease support” from us. Lease support will help you get a “guarantor” or a 3rd party organization that will co-sign the lease with you. You are still responsible for all rent payments, but the 3rd party organization will help tell the landlord that they trust you to make the repayments. If you are unable to pay rent one month, the 3rd party organization will provide the rent for 1 month and this will have to be repaid by you later.</p>

<p>If your application for lease support is accepted, we will help you contact the guarantor and finalize this partnership.</p>

<p>Please enter the details of your proposed lease below:<p>
<ol>
	<li>What is the length of the proposed lease?</li>
	<li>What is the rent of the proposed lease?</li>
	<li>How many months is the lease?</li>
</ol>


  <form method="post">
  	{% csrf_token %}
  	{{ lease_form.as_p }}
  	<input type="hidden" name="action" value="lease-app">
  	<button type="submit" class="btn btn-primary">Submit Lease Support Application</button>
  </form>

  {% endif %}

{% endblock %}

core/templates/core/leaser_view.html
{% extends 'core/base/base.html' %}


{% block content %}

{% if access %}

<h1>{{ user.account.name }}'s Profile</h1>

<hr>

<h2>Creditability Score: {{ profile.credit_score }}</h2>

<p>Name: {{ profile.name }}</p>
<p>City: {{ profile.city }}</p>
<p>Country: {{ profile.country }}</p>
<p>Phone: {{ profile.phone }}</p>
<p>Age: {{ profile.age }}</p>

<p>Profile Photo:</p>
<img src="{{profile.profile_photo.url}}" style="width:50%">
<hr>

{% else %}

<h4>You no longer have access to this account.</h4>

{% endif %}

{% endblock %}

core/templates/core/login.html
{% extends 'core/base/base.html' %}

{% block content %}
  <h1>Login</h1>
  <hr>
  <form method="post">
    {% csrf_token %}
    {{ login_form.as_p }}
    <button type="submit" class="btn btn-primary">Login</button>
  </form>

  <hr>

  <p>Not signed up? <a href="{% url 'register' %}">Create an Account</a></p>
{% endblock %}

core/templates/core/register.html
{% extends 'core/base/base.html' %}

{% block content %}
  <h1>Register</h1>
  <hr>
  <form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    <button type="submit" class="btn btn-primary">Sign Up</button>
  </form>
{% endblock %}